### ISSUE TITLE
Error when submitting document

### ISSUE THREAD

**Issue by cbetta** [interfax/interfax-python#5]
I get an error with the following code sample (with my own API keys and fax number)

```py
from interfax import InterFAX
import os

interfax = InterFAX(
    username="username",
    password="password"
)

# create a new InterFAX Document
document = interfax.documents.create(
    "test.pdf",
    os.stat("test.pdf").st_size
)

# read the file to send
with open("test.pdf", "rb") as fp:
    cursor = 0
    while True:
        chunk = fp.read(500)
        if not chunk:
            break
        next_cursor = cursor + len(chunk)
        # upload each chunk
        document.upload(cursor, next_cursor-1, chunk)
        cursor = next_cursor

# send the fax
interfax.deliver(
  # a valid fax number
  fax_number="11222333444",
  # the document URI
  files=[document.uri]
)
```

The error is:

```sh
Traceback (most recent call last):
  File "extra_4_send_a_large_file_and_monitor_progress.py", line 34, in <module>
    files=[document.uri]
  File "/Users/cbetta/.pyenv/versions/3.5.3/lib/python3.5/site-packages/interfax/outbound.py", line 20, in deliver
    files=self._generate_files(files))
  File "/Users/cbetta/.pyenv/versions/3.5.3/lib/python3.5/site-packages/interfax/client.py", line 76, in post
    return self._request('POST', url, **kwargs)
  File "/Users/cbetta/.pyenv/versions/3.5.3/lib/python3.5/site-packages/interfax/client.py", line 89, in _request
    return self._parse_response(request(method, url, **kwargs))
  File "/Users/cbetta/.pyenv/versions/3.5.3/lib/python3.5/site-packages/interfax/client.py", line 117, in _parse_response

    response.raise_for_status()
  File "/Users/cbetta/.pyenv/versions/3.5.3/lib/python3.5/site-packages/requests/models.py", line 909, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://rest.interfax.net/outbound/faxes?faxNumber=11222333444
```

Any idea @danielknell ?

**Comment by ricky-shake-n-bake-bobby** [comment]
This issue has been resolved with the release of v1.0.1.
